logging:
  level:
    org:
      springframework:
        security: DEBUG
        cloud:
          gateway:
            route:
              RouteDefinitionLocator: INFO
            nodeValue: TRACE
    root: info
  #Configuring logging pattern:
  pattern:
    level: "%5p [${spring.application.name:}, %X{traceId:-},%X{spanId:-}]"


spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/youtube-microservices-project


  cloud:
    gateway:
      routes[2]:
        uri: lb://inventory-service
        predicates[0]: Path=/api/inventories/**
      routes[3]:
        predicates[0]: Path=/eureka/web
        filters[0]: SetPath=/
        uri: http://localhost:8761
      routes[1]:
        predicates[0]: Path=/api/orders/**
        uri: lb://order-service
      routes[4]:
        uri: http://localhost:8761
        predicates[0]: Path=/eureka/**
      routes[0]:
        uri: lb://product-service
        predicates[0]: Path=/api/products/**
  application:
    name: api-gateway


server:
  port: '8765'


eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:password@localhost:8761/eureka



#Configuring the percentage
management:
  tracing:
    sampling:
      probability: 1.0

